version: '2'

services:
  front:
    container_name: front
    build: ../opg-lpa-front
    # image: registry.service.opg.digital/opguk/lpa-front:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - ../lpa-local-dev/develop/env/front.env
      - ../lpa-local-dev/develop/env/base.env
    volumes:
      - ../opg-lpa-front:/app:cached
      - ../opg-lpa-api-client:/client:cached
